USE test;

DROP TABLE IF EXISTS `Book`;
CREATE TABLE `Book` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `AUTHOR` varchar(100) NOT NULL,
  `ISBN` varchar(20) DEFAULT NULL,
  `PRINT_YEAR` int(11) NOT NULL,
  `READ_ALREADY` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8;


LOCK TABLES `Book` WRITE;
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Изучаем Java', 'Это не просто книга. Она не только научит вас теории языка Java и объектно-ориентированного программирования, она сделает вас программистом.', 'Кэти Сиерра', '978-5-699-54574-2', 2017, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Java 8. Полное руководство', 'Книга Java 8. Полное руководство является исчерпывающим руководством по программированию на языке Java.', 'Герберт Шилдт', '978-5-8459-1918-2', 2017, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Java 8. Руководство для начинающих', 'Настоящее, 6-е издание бестселлера Герберта Шилдта "Java 8. Руководство для начинающих", обновленное с учетом всех новинок последнего выпуска Java Platform', 'Герберт Шилдт', '978-5-8459-1955-7', 2017, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Структуры данных и алгоритмы в Java', 'Второе издание одной из самых авторитетных книг по программированию посвящено использованию структур данных и алгоритмов.', 'Роберт Лафоре', '978-5-496-00740-5', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Java 8. Карманный справочник', 'КАРМАННЫЙ СПРАВОЧНИК послужит вам удобным справочником по стандартным возможностям языка программирования Java и его платформы.', 'Роберт Лигуори', '978-5-8459-2050-8', 2012, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Java. Эффективное программирование', 'Первое издание книги "Java. Эффективное программирование", содержащей пятьдесят семь ценных правил, предлагает решение задач программирования, с которыми большинство разработчиков сталкиваются каждый день.', 'Джошуа Блох', '978-5-85582-347-9', 2014, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Изучаем Java EE 7', 'Java Enterprise Edition (Java EE) остается одной из ведущих технологий и платформ на основе Java.', 'Энтони Гонсалвес', '978-5-496-00942-3', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Spring 4 для профессионалов', 'Книга представляет собой многолетний бестселлер, который обновлен с целью отражения функциональных средств, предлагаемых последней версией платформы Spring Framework 4.', 'Крис Шефер', '978-1-4302-6151-3', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Spring в действии', 'Фреймворк Spring Framework - необходимый инструмент для разработчиков приложений на Java.', 'Крейг Уоллс', '978-1-9351-8235-1', 2015, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Лямбда-выражения в Java 8', 'Из этой книги узнаете об изменениях в версии Java 8, обусловленных появлением в языке лямбда-выражении', 'Ричард Уорбэртон', '978-5-97060-463-2', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Java. Серверные приложения', 'В книге описаны практические вопросы, посвященные работе с Java-серверными приложениями', 'Равиль Мухамедзянов', '', 2014, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Алгоритмы на Java', 'Алгоритмы на Java является классическим справочным руководством в котором содержится необходимый объем знаний для программиста в области алгоритмов', 'Роберт Седжвик', '978-5-8459-2049-2', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Web-сервисы Java', 'Рассмотрены основы технологии Web-сервисов в спецификациях первого и второго уровня', 'Тимур Машнин', '978-5-9775-0778-3', 2012, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Professional Apache Tomcat 6', 'Tomcat is the official reference implementation of Sun''s servlet and JSP specifications, and Java developers must test all Web', 'Вивек Чопра', '978-0-471-75361-2', 2013, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Клан белого волка', 'Дядя Эдик отказывается выбрасывать дохлую нечисть с нашего балкона! Он вообще не понимает, как это выбрасывать то, что можно замариновать и съесть?', 'Андрей Белянин', '978-5-9922-2209-8', 2016, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Ночь на хуторе близ Диканьки', 'Старая рукопись, купленная по случаю на антикварном рынке, оставила по прочтении слишком много вопросов... На что способны двое друзей - кузнец и гимназист?', 'Андрей Белянин', '978-5-9922-2313-2', 2015, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Пуля для императора', 'Молодой граф Михаил Строгов продолжает свое путешествие по России, стремясь разгадать тайну записных книжек своего отца. И узнает о предстоящем покушении на императора', 'Андрей Белянин', '978-5-17-087597-9', 2014, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Цепные псы Империи', 'Потомственный дворянин, молодой граф Строгов возвращается из Англии согласно воле умирающего отца и узнает о том, что принадлежит тайному ордену, который защищает Россию.', 'Андрей Белянин', '978-5-17-087596-2', 2011, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Оно', 'Маленький американский городок Дерри. Семеро друзей создают "Клуб неудачников". У каждого из них есть своя проблема, обрекающая на одиночество и насмешки, - заикание, астма, лишний вес, близорукость', 'Стивен Кинг', '978-5-17-105218-8', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Мертвая зона', 'Столкновение на льду обернулось для Джона Смита сотрясением мозга. С тех пор его неизменно преследуют страшные видения.', 'Стивен Кинг', '978-5-17-080577-8', 2012, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('В режиме бога', 'Виктор Сигалов пишет морфоскрипты - интерактивные сны, заменившие людям игры, кино и книги. Как все авторы, он считает себя гением и втайне мечтает создать виртуальную реальность, равную реальному миру.', 'Евгений Прошкин', '978-5-906716-62-0', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Мир Стругацких. Рассвет и Полдень', 'Таинственный незнакомец открывает молодому астроному ужасающую правду о грядущей судьбе человечества. Верить ли пришельцу из будущего или... продолжать заниматься своим делом?', 'Игорь Минаков', '978-5-699-94510-8', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Русская фантастика - 2017', 'Бродячего кота прозвали Чумой, но Максим назвал его Рыжим, приютил, обогрел, накормил. И не прогадал! Вскоре выяснилось, что только кот Рыжий способен выручить человека из беды, в ситуации, находящейся явно за пределами человеческих возможностей', 'Игорь Минаков', '978-5-699-93785-1', 2017, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Почти идеальные люди', 'Самая нашумевшая нон-фикшн книга о Скандинавии. Переведено на 6 языков Продано 1 000 000 экземляров Почему датчане счастливы, хотя у них такие высокие налоги? На что норвежцы тратят свое невероятное богатство? ', 'Майкл Бут', '978-5-699-98691-0', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Русский дневник', '"Русский дневник" лауреата Пулитцеровской премии писателя Джона Стейнбека и известного военного фотографа Роберта Капы - это классика репортажа и путевых заметок.', 'Джон Стейнбек', '978-5-699-93270-2', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Шахматы для детей', 'Герои этой красочной книги с обворожительными авторскими иллюстрациями в легкой игровой форме рассказывают детям об основных шахматных правилах, о разных фигурах и о том, как они ходят, приводят некоторые шахматные хитрости', 'Сабрина Чеваннес', '978-5-699-78107-2', 2015, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Эверест. Смертельное восхождение', 'Трагические события мая 1996 г. на Эвересте - это история столкновения запредельных амбиций, стальной воли, фатальных ошибок и небывалой самоотверженности. Международная экспедиция неожиданно обернулась катастрофой', 'Анатолий Букреев', '978-5-699-84417-3', 2015, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('В поисках кадра', 'Цель этой книги - не только раскрыть возможности фотографии, но и преодолеть привычку смотреть на вещи традиционно, делая скучные, унылые снимки. ', 'Брайан Петерсон', '978-5-00100-759-3', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Тренируем мозг', 'О книге Простая система развития интеллекта, основанная на научных исследованиях профессора и ведущего японского специалиста по томографии мозга.', 'Рюта Кавашима', '978-5-00100-320-5', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Мозг Леонардо.', 'Хирург и автор бестселлеров Леонард Шлейн предпринимает попытку изучить интеллект выдающегося человека Возрождения, связывая истоки его творческих способностей с устройством мозга…', 'Леонард Шлейн', '978-5-91671-549-1', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Microsoft Windows Server 2012 R2', 'Данная книга - краткий и исчерпывающий справочник по администрированию Windows Server 2012 R2. Описаны управление файловыми системами и дисками, настройка носителей данных, общий доступ к данным и избыточность, безопасность данных и аудит', 'Уильям Р. Станек', '978-5-9775-3558-8', 2015, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Командная строка Linux', 'Уильям Шоттс знакомит вас с истинной философией Linux.', 'Уильям Шоттс', '978-5-496-02303-0', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Внутреннее устройство Linux', 'Книга представляет собой введение во внутреннее устройство операционной системы Linux. Все положения наглядно проиллюстрированы примерами, разработанными автором и проверенными им на практике.', 'Дмитрий Кетов', '978-5-9775-3580-9', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Unix и Linux', 'Новое издание всемирно известной книги «Unix и Linux: руководство системного администратора» признанных авторитетов в области системного администрирования систем UNIX и Linux содержит точную и полную информацию о практически всех аспектах', 'Бэн Уэйли', '978-5-8459-1740-9', 2014, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Чистый код', 'Даже плохой программный код может работать. Однако если код не является "чистым", это всегда будет мешать развитию проекта и компании-разработчика, отнимая значительные ресурсы на его поддержку и "укрощение"', 'Роберт К. Мартин', '978-0332350884', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Грокаем алгоритмы', 'Алгоритмы - это всего лишь пошаговые алгоритмы решения задач, и большинство таких задач уже были кем-то решены, протестированы и проверены.', 'Адитья Бхаргава', '978-5-496-02541-6', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('Совершенный код', 'Более 10 лет первое издание этой книги считалось одним из лучших практических руководств по программированию. Сейчас эта книга полностью обновлена с учетом современных тенденций и технологий и дополнена сотнями новых примеров', 'Стив Макконнелл', '978-5-7502-0064-1', 2017, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('5555551Update', '555555', '5511', '55555', 2016, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('44412', '555', '666', '777', 1999, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('444', '444', '444', '444', 2015, 1);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('666666', '98987987', 'fdklghlksj', 'ew345gf', 2012, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('987987987', 'kjhkjhkjhj', ';llklkjlkjkjhj', 'kjhkj', 2012, 0);
INSERT INTO test.Book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR, READ_ALREADY) VALUES ('987987987', 'kjhkjhkjhj', ';llklkjlkjkjhj', 'kjhkj', 2012, 0);
UNLOCK TABLES;
